import {StyleSheet} from 'react-native';

const BUTTON_COLOR = '#c6c7cb';
const BUTTON_TEXT_COLOR = '#344054';

export const styles = StyleSheet.create({
  card: {
    backgroundColor: '#FFF',
    borderRadius: 10,
    shadowColor: 'rgba(18, 18, 23, 0.06)',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 1,
    shadowRadius: 2,
    elevation: 3,
    margin: 10,
    padding: 15,
    flex: 1,
    width: 23 * 16, 
    padding: 16, 
    flexDirection: 'column',
    alignItems: 'flex-start',
    marginVertical: 4, 
    gap:8,
  },
  propertyImage: {
    width: '100%',
    height: 150,
    borderRadius: 10,
  },
  priceText: {
    color: '#850C70',
    // fontFeatureSettings: 'liga off, clig off',
    // fontFamily: 'DIN Next LT Pro',
    fontSize: 20, 
    fontStyle: 'normal',
    fontWeight: '500',
    lineHeight: 22,
    letterSpacing: -0.025,
    marginTop: 5,
  },
  detailsText: {
    fontSize: 16,
    color: 'black',
    marginTop: 5,
    fontSize: 16, 
    fontStyle: 'normal',
    fontWeight: '400',
    lineHeight: 22,
    letterSpacing: -0.025,
  },
  detailsAddress: {
    fontSize: 10,
    color: '#667085',
    marginTop: 5,
    fontSize: 16, 
    fontStyle: 'normal',
    fontWeight: '400',
    lineHeight: 22,
    letterSpacing: -0.025,
  },
  detailsCarpet: {
    fontSize: 12,
    paddingLeft:10,
    backgroundColor: '#FBF8F0',
    color: 'black', 
    marginTop: 5,
    fontStyle: 'normal',
    fontWeight: '400',
    lineHeight: 22,
    letterSpacing: -0.025,
  },
  
  amenities: {
    flexDirection: 'row',  
    alignItems: 'center',  
    justifyContent: 'center', 
    marginTop: 10,           
  },
  amenityImage: {
    width: 40,            
    height: 40,            
    margin: 5,              
  },
  buttonsContainer: {
    position: 'absolute',
    top:115,
    
    right: 20,
    flexDirection: 'row',
  },
  button: {
    flexDirection:'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: BUTTON_COLOR,
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderRadius: 8,
    margin: 5,
  },
  buttonText: {
    color: BUTTON_TEXT_COLOR,
    fontFamily: 'DIN Next LT Pro',
    fontSize: 13,
    fontWeight: '400',
    lineHeight: 18,
    letterSpacing: -0.4,
    textAlign: 'left',
    paddingRight:6,
    paddingHorizontal:5,
  },
});
